<?php

/*
 |--------------------------------------------------------------------------
 | DO NOT EDIT THIS FILE DIRECTLY.
 |--------------------------------------------------------------------------
 | This file reads from your .env configuration file and should not
 | be modified directly.
*/

return [

    /*
    |--------------------------------------------------------------------------
    | Third Party Services
    |--------------------------------------------------------------------------
    |
    | This file is for storing the credentials for third party services such
    | as Stripe, Mailgun, Mandrill, and others. This file provides a sane
    | default location for this type of information, allowing packages
    | to have a conventional place to find your various credentials.
    |
    */

    'mailgun' => [
        'domain' => env('MAILGUN_DOMAIN'),
        'secret' => env('MAILGUN_SECRET'),
        'endpoint' => env('MAILGUN_ENDPOINT', 'api.mailgun.net'),
    ],

    'mandrill' => [
        'secret' => env('MANDRILL_SECRET'),
    ],

    'ses' => [
        'key' => env('AWS_ACCESS_KEY_ID'),
        'secret' => env('AWS_SECRET_ACCESS_KEY'),
        'region' => env('AWS_DEFAULT_REGION', 'us-east-1'),
    ],

    'stripe' => [
        'model'  => App\User::class,
        'key'    => env('STRIPE_KEY'),
        'secret' => env('STRIPE_SECRET'),
    ],

    'google' => [
        'maps_api_key' => env('GOOGLE_MAPS_API'),
    ],

    'oidc' => [
        'enabled' => env('OIDC_ENABLED', false),
        'discovery_url' => env('OIDC_DISCOVERY_URL'),
        'issuer' => env('OIDC_ISSUER', env('OAUTH_ISSUER_URI')),
        'client_id' => env('OIDC_CLIENT_ID', env('OAUTH_CLIENT_ID')),
        'client_secret' => env('OIDC_CLIENT_SECRET', env('OAUTH_CLIENT_SECRET')),
        'redirect' => env('OIDC_REDIRECT_URI'),
        'scopes' => env('OIDC_SCOPES', 'openid profile email'),
        'username_claim' => env('OIDC_USERNAME_CLAIM', 'preferred_username'),
        'login_label' => env('OIDC_LOGIN_LABEL', 'Login with SSO'),
    ],

];
